# %%
import pandas as pd
columns = {
    "MOTIVO":object,
    "NUMERO_ACTA_CONTROL":object,
    "NUMERO_ACTA_VISITA":object,
    "FECHA_VISITA":object,
    "FECHA_INGRESO":object,
    "RAZON_SOCIAL":object,
    "CEDULA_NIT":object,
    "NOMBRE_COMERCIAL":object,
    "MATRICULA_MERCANTIL":object,
    "NUMERO_INSCRIPCION":object,
    "DIRECCION":object,
    "DEPARTAMENTO":object,
    "MUNICIPIO":object,
    "ZONA":object,
    "BARRIO":object,
    "TELEFONO":object,
    "NOMBRE_PROPIETARIO":object,
    "EMPTY":object,
    "DOCUMENTO_IDENTIFICACION":object,
    "NOMBRE_REPRESENTANTE_LEGAL":object,
    "DOCUMENTO_IDENTIFICACION2":object,
    "DIRECCION_NOTIFICACION":object,

    "LOCALIZACION_Y_CONSTRUCCION_A":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_AR":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_I":"float64",

    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_AR":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_I":"float64",

    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_A":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_AR":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_I":"float64",

    "INSTALACIONES_SANITARIAS_1_A":"float64",
    "INSTALACIONES_SANITARIAS_1_AR":"float64",
    "INSTALACIONES_SANITARIAS_1_I":"float64",

    "INSTALACIONES_SANITARIAS_2_A":"float64",
    "INSTALACIONES_SANITARIAS_2_AR":"float64",
    "INSTALACIONES_SANITARIAS_2_I":"float64",

    "EDIFICACION_E_INSTALACIONES":"float64",

    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_A":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_AR":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_I":"float64",

    "SUPERFICIE_CONCATO_ALIMENTO_A":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_AR":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_I":"float64",

    "EQUIPOS_Y_UTENSILIOS":"float64",

    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_A":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_AR":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_I":"float64",

    "RECONOCIMIENTO_MEDICO_A":"float64",
    "RECONOCIMIENTO_MEDICO_AR":"float64",
    "RECONOCIMIENTO_MEDICO_I":"float64",

    "PRACTICAS_HIGIENICAS_Y_DOTACION_A":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_AR":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_I":"float64",

    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_A":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_AR":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_I":"float64",

    "PERSONAL_MANIPULADOR_DE_ALIMENTOS":"float64",

    "SUMINISTRO_CALIDAD_AGUA_POTABLE_A":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_AR":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_I":"float64",

    "RESIDUOS_LIQUIDOS_A":"float64",
    "RESIDUOS_LIQUIDOS_AR":"float64",
    "RESIDUOS_LIQUIDOS_I":"float64",

    "RESIDUOS_SOLIDOS_A":"float64",
    "RESIDUOS_SOLIDOS_AR":"float64",
    "RESIDUOS_SOLIDOS_I":"float64",

    "CONTROL_INTEGRAL_PLAGAS_A":"float64",
    "CONTROL_INTEGRAL_PLAGAS_I":"float64",

    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_A":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_AR":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_I":"float64",

    "SOPORTE_DOCUMENTALES_SANEAMIENTO_A":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_AR":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_I":"float64",

    "SANEAMIENTO":object,

    "CONDICIONES_ALMACENAMIENTO_A":object,
    "CONDICIONES_ALMACENAMIENTO_AR":"float64",
    "CONDICIONES_ALMACENAMIENTO_I":"float64",

    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_A":"float64",
    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_AR":"float64",
    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_I":"float64",

    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_A":"float64",
    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_AR":"float64",
    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_I":"float64",

    "ALMACENAMIENTO_Y_COMERCIALIZACION":"float64",

    "PROCEDENCIA_REQUISITOS_LEGALES_A":"float64",
    "PROCEDENCIA_REQUISITOS_LEGALES_AR":"float64",
    "PROCEDENCIA_REQUISITOS_LEGALES_I":"float64",

    "REQUISITOS_LEGALES":"float64",

    "PORCENTAJE_CUMPLIMIENTO":"float64",
    "CUMPLIMIENTO_FAVORABLE_90_100":object,
    "CUMPLIMIENTO_FAVORABLE_80_90":object,
    "CUMPLIMIENTO_FAVORABLE_70_80":object,
    "CUMPLIMIENTO_FAVORABLE_60_70":object,
    "CUMPLIMIENTO_FAVORABLE_0_60":object,
    "REPONSABLE":object,
    "MEDIDA_SANITARIA":object
}
df_historico_tiendas = pd.read_excel("../data/BASE DE DATOS IVC(INSPECCION VIGILANCIA Y CONTROL) 2020.xlsx","TIENDAS",skiprows=3,engine='openpyxl', header=None, names=list(columns.keys()), index_col=None, dtype=columns)
df_historico_tiendas["SANEAMIENTO"] = df_historico_tiendas.SANEAMIENTO.apply(lambda x: str(x).replace("..", ".")).astype("float64")
df_historico_tiendas.CONDICIONES_ALMACENAMIENTO_A = df_historico_tiendas.CONDICIONES_ALMACENAMIENTO_A.replace({"O":"0"}).astype("float64")
df_historico_tiendas["TIPO"] = "tiendas"

# %%
# counter = 0
# for row in df_historico.iterrows():
#     counter+=1
#     if counter==10:
#         break
# counter

# %%
import pandas as pd
pd.set_option("max_columns",0)
columns = {
    "MOTIVO":object,
    "NUMERO_ACTA_CONTROL":object,
    "FECHA_VISITA":object,
    "FECHA_INGRESO":object,
    "RAZON_SOCIAL":object,
    "CEDULA_NIT":object,
    "NOMBRE_COMERCIAL":object,
    "MATRICULA_MERCANTIL":object,
    "NUMERO_INSCRIPCION":object,
    "DIRECCION":object,
    "DEPARTAMENTO":object,
    "MUNICIPIO":object,
    "ZONA":object,
    "BARRIO":object,
    "TELEFONO":object,
    "NOMBRE_PROPIETARIO":object,
    "DOCUMENTO_IDENTIFICACION":object,
    "NOMBRE_REPRESENTANTE_LEGAL":object,
    "DOCUMENTO_IDENTIFICACION2":object,
    "DIRECCION_NOTIFICACION":object,

    "LOCALIZACION_Y_CONSTRUCCION_A":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_AR":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_I":"float64",

    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_AR":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_I":"float64",

    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_A":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_AR":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_I":"float64",

    "INSTALACIONES_SANITARIAS_1_A":"float64",
    "INSTALACIONES_SANITARIAS_1_AR":"float64",
    "INSTALACIONES_SANITARIAS_1_I":"float64",

    "EDIFICACION_E_INSTALACIONES":"float64",

    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_A":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_AR":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_I":"float64",

    "SUPERFICIE_CONCATO_ALIMENTO_A":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_AR":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_I":"float64",

    "EQUIPOS_Y_UTENSILIOS":"float64",

    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_A":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_AR":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_I":"float64",

    "RECONOCIMIENTO_MEDICO_A":"float64",
    "RECONOCIMIENTO_MEDICO_AR":"float64",
    "RECONOCIMIENTO_MEDICO_I":"float64",

    "PRACTICAS_HIGIENICAS_Y_DOTACION_A":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_AR":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_I":"float64",

    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_A":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_AR":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_I":"float64",

    "PERSONAL_MANIPULADOR_DE_ALIMENTOS":"float64",

    "CONTROL_MATERIAS_PRIMAS_INSUMOS_A":"float64",
    "CONTROL_MATERIAS_PRIMAS_INSUMOS_AR":"float64",
    "CONTROL_MATERIAS_PRIMAS_INSUMOS_I":"float64",

    "PREVENCION_CONTAMINACION_A":"float64",
    "PREVENCION_CONTAMINACION_I":"float64",

    "MANEJO_TEMPERATURAS_A":"float64",
    "MANEJO_TEMPERATURAS_AR":"float64",
    "MANEJO_TEMPERATURAS_I":"float64",

    "CONDICIONES_ALMACENAMIENTO_A":"float64",
    "CONDICIONES_ALMACENAMIENTO_AR":"float64",
    "CONDICIONES_ALMACENAMIENTO_I":"float64",

    "REQUISITOS_HIGIENICOS": "float64",

    "SUMINISTRO_CALIDAD_AGUA_POTABLE_A":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_AR":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_I":"float64",

    "RESIDUOS_LIQUIDOS_A":"float64",
    "RESIDUOS_LIQUIDOS_AR":object,
    "RESIDUOS_LIQUIDOS_I":object,

    "RESIDUOS_SOLIDOS_A":"float64",
    "RESIDUOS_SOLIDOS_AR":"float64",
    "RESIDUOS_SOLIDOS_I":"float64",

    "CONTROL_INTEGRAL_PLAGAS_A":"float64",
    "CONTROL_INTEGRAL_PLAGAS_I":"float64",

    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_A":object,
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_AR":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_I":object,

    "SOPORTE_DOCUMENTALES_SANEAMIENTO_A":object,
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_AR":object,
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_I":object,

    "SANEAMIENTO":object,

    "PORCENTAJE_CUMPLIMIENTO":object,
    "CUMPLIMIENTO_FAVORABLE_90_100":object,
    "CUMPLIMIENTO_FAVORABLE_80_90":object,
    "CUMPLIMIENTO_FAVORABLE_70_80":object,
    "CUMPLIMIENTO_FAVORABLE_60_70":object,
    "CUMPLIMIENTO_FAVORABLE_0_60":object,

    "REPONSABLE":object,
    "MEDIDA_SANITARIA":object
}
df_historico_panaderias = pd.read_excel("../data/BASE DE DATOS IVC(INSPECCION VIGILANCIA Y CONTROL) 2020.xlsx","PANADERIAS",skiprows=3,engine='openpyxl', header=None, names=list(columns.keys()), index_col=None, dtype=columns)
df_historico_panaderias["TIPO"] = "panaderias"


# %%
import pandas as pd
pd.set_option("max_columns",0)
columns = {
    "MOTIVO":object,
    "NUMERO_ACTA_CONTROL":object,
    "FECHA_VISITA":object,
    "FECHA_INGRESO":object,
    "RAZON_SOCIAL":object,
    "CEDULA_NIT":object,
    "NOMBRE_COMERCIAL":object,
    "MATRICULA_MERCANTIL":object,
    "NUMERO_INSCRIPCION":object,
    "DIRECCION":object,
    "DEPARTAMENTO":object,
    "MUNICIPIO":object,
    "ZONA":object,
    "BARRIO":object,
    "TELEFONO":object,
    "NOMBRE_PROPIETARIO":object,
    "DOCUMENTO_IDENTIFICACION":object,
    "NOMBRE_REPRESENTANTE_LEGAL":object,
    "DOCUMENTO_IDENTIFICACION2":object,
    "DIRECCION_NOTIFICACION":object,

    "LOCALIZACION_Y_CONSTRUCCION_A":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_AR":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_I":"float64",

    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_AR":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_I":"float64",

    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_A":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_AR":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_I":"float64",

    "INSTALACIONES_SANITARIAS_1_A":"float64",
    "INSTALACIONES_SANITARIAS_1_AR":"float64",
    "INSTALACIONES_SANITARIAS_1_I":"float64",

    "EDIFICACION_E_INSTALACIONES":"float64",

    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_A":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_AR":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_I":"float64",

    "SUPERFICIE_CONCATO_ALIMENTO_A":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_AR":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_I":"float64",

    "EQUIPOS_Y_UTENSILIOS":"float64",

    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_A":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_AR":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_I":"float64",

    "RECONOCIMIENTO_MEDICO_A":"float64",
    "RECONOCIMIENTO_MEDICO_AR":"float64",
    "RECONOCIMIENTO_MEDICO_I":"float64",

    "PRACTICAS_HIGIENICAS_Y_DOTACION_A":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_AR":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_I":"float64",

    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_A":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_AR":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_I":"float64",

    "PERSONAL_MANIPULADOR_DE_ALIMENTOS":"float64",

    "CONTROL_MATERIAS_PRIMAS_INSUMOS_A":"float64",
    "CONTROL_MATERIAS_PRIMAS_INSUMOS_AR":"float64",
    "CONTROL_MATERIAS_PRIMAS_INSUMOS_I":"float64",

    "PREVENCION_CONTAMINACION_A":"float64",
    "PREVENCION_CONTAMINACION_I":"float64",

    "MANEJO_TEMPERATURAS_A":"float64",
    "MANEJO_TEMPERATURAS_AR":"float64",
    "MANEJO_TEMPERATURAS_I":"float64",

    "CONDICIONES_ALMACENAMIENTO_A":"float64",
    "CONDICIONES_ALMACENAMIENTO_AR":"float64",
    "CONDICIONES_ALMACENAMIENTO_I":"float64",

    "REQUISITOS_HIGIENICOS": "float64",

    "SUMINISTRO_CALIDAD_AGUA_POTABLE_A":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_AR":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_I":"float64",

    "RESIDUOS_LIQUIDOS_A":"float64",
    "RESIDUOS_LIQUIDOS_AR":"float64",
    "RESIDUOS_LIQUIDOS_I":"float64",

    "RESIDUOS_SOLIDOS_A":"float64",
    "RESIDUOS_SOLIDOS_AR":"float64",
    "RESIDUOS_SOLIDOS_I":"float64",

    "CONTROL_INTEGRAL_PLAGAS_A":"float64",
    "CONTROL_INTEGRAL_PLAGAS_I":"float64",

    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_A":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_AR":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_I":"float64",

    "SOPORTE_DOCUMENTALES_SANEAMIENTO_A":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_AR":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_I":"float64",

    "SANEAMIENTO":"float64",

    "PORCENTAJE_CUMPLIMIENTO":"float64",
    "CUMPLIMIENTO_FAVORABLE_90_100":object,
    "CUMPLIMIENTO_FAVORABLE_80_90":object,
    "CUMPLIMIENTO_FAVORABLE_70_80":object,
    "CUMPLIMIENTO_FAVORABLE_60_70":object,
    "CUMPLIMIENTO_FAVORABLE_0_60":object,

    "REPONSABLE":object,
    "MEDIDA_SANITARIA":object,
    "EMPTY1":object,
    "EMPTY2":object,
}
df_historico_restaurantes = pd.read_excel("../data/BASE DE DATOS IVC(INSPECCION VIGILANCIA Y CONTROL) 2020.xlsx","RESTAURANTES",skiprows=3,engine='openpyxl', header=None, names=list(columns.keys()), index_col=None, dtype=columns)
df_historico_restaurantes["TIPO"] = "restaurantes"

# %%
import pandas as pd
pd.set_option("max_columns",0)
columns = {
    "MOTIVO":object,
    "NUMERO_ACTA_CONTROL":object,
    "FECHA_VISITA":object,
    "FECHA_INGRESO":object,
    "RAZON_SOCIAL":object,
    "CEDULA_NIT":object,
    "NOMBRE_COMERCIAL":object,
    "MATRICULA_MERCANTIL":object,
    "NUMERO_INSCRIPCION":object,
    "DIRECCION":object,
    "DEPARTAMENTO":object,
    "MUNICIPIO":object,
    "ZONA":object,
    "BARRIO":object,
    "TELEFONO":object,
    "NOMBRE_PROPIETARIO":object,
    "DOCUMENTO_IDENTIFICACION":object,
    "NOMBRE_REPRESENTANTE_LEGAL":object,
    "DOCUMENTO_IDENTIFICACION2":object,
    "DIRECCION_NOTIFICACION":object,

    "LOCALIZACION_Y_CONSTRUCCION_A":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_AR":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_I":"float64",

    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_AR":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_I":"float64",

    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_A":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_AR":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_I":"float64",

    "INSTALACIONES_SANITARIAS_1_A":"float64",
    "INSTALACIONES_SANITARIAS_1_AR":"float64",
    "INSTALACIONES_SANITARIAS_1_I":"float64",

    "EDIFICACION_E_INSTALACIONES":"float64",

    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_A":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_AR":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_I":"float64",

    "SUPERFICIE_CONCATO_ALIMENTO_A":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_AR":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_I":"float64",

    "EQUIPOS_Y_UTENSILIOS":"float64",

    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_A":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_AR":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_I":"float64",

    "RECONOCIMIENTO_MEDICO_A":"float64",
    "RECONOCIMIENTO_MEDICO_AR":"float64",
    "RECONOCIMIENTO_MEDICO_I":object,

    "PRACTICAS_HIGIENICAS_Y_DOTACION_A":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_AR":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_I":"float64",

    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_A":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_AR":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_I":"float64",

    "PERSONAL_MANIPULADOR_DE_ALIMENTOS":"float64",

    "CONTROL_MATERIAS_PRIMAS_INSUMOS_A":"float64",
    "CONTROL_MATERIAS_PRIMAS_INSUMOS_AR":"float64",
    "CONTROL_MATERIAS_PRIMAS_INSUMOS_I":"float64",

    "PREVENCION_CONTAMINACION_A":"float64",
    "PREVENCION_CONTAMINACION_I":"float64",

    "MANEJO_TEMPERATURAS_A":"float64",
    "MANEJO_TEMPERATURAS_AR":"float64",
    "MANEJO_TEMPERATURAS_I":"float64",

    "CONDICIONES_ALMACENAMIENTO_A":"float64",
    "CONDICIONES_ALMACENAMIENTO_AR":"float64",
    "CONDICIONES_ALMACENAMIENTO_I":"float64",

    "REQUISITOS_HIGIENICOS": "float64",

    "SUMINISTRO_CALIDAD_AGUA_POTABLE_A":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_AR":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_I":"float64",

    "RESIDUOS_LIQUIDOS_A":"float64",
    "RESIDUOS_LIQUIDOS_AR":"float64",
    "RESIDUOS_LIQUIDOS_I":"float64",

    "RESIDUOS_SOLIDOS_A":"float64",
    "RESIDUOS_SOLIDOS_AR":"float64",
    "RESIDUOS_SOLIDOS_I":"float64",

    "CONTROL_INTEGRAL_PLAGAS_A":"float64",
    "CONTROL_INTEGRAL_PLAGAS_I":"float64",

    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_A":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_AR":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_I":"float64",

    "SOPORTE_DOCUMENTALES_SANEAMIENTO_A":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_AR":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_I":"float64",

    "SANEAMIENTO":"float64",

    "PORCENTAJE_CUMPLIMIENTO":"float64",
    "CUMPLIMIENTO_FAVORABLE_90_100":object,
    "CUMPLIMIENTO_FAVORABLE_80_90":object,
    "CUMPLIMIENTO_FAVORABLE_70_80":object,
    "CUMPLIMIENTO_FAVORABLE_60_70":object,
    "CUMPLIMIENTO_FAVORABLE_0_60":object,

    "REPONSABLE":object,
    "MEDIDA_SANITARIA":object,
    "EMPTY1":object,
    "EMPTY2":object,
}
df_historico_comidas_rapidas = pd.read_excel("../data/BASE DE DATOS IVC(INSPECCION VIGILANCIA Y CONTROL) 2020.xlsx","COMIDAS RÁPIDAS",skiprows=3,engine='openpyxl', header=None, names=list(columns.keys()), index_col=None, dtype=columns)
df_historico_comidas_rapidas["RECONOCIMIENTO_MEDICO_I"] =  df_historico_comidas_rapidas.RECONOCIMIENTO_MEDICO_I.replace("'O'", "0")
df_historico_comidas_rapidas["RECONOCIMIENTO_MEDICO_I"] =  df_historico_comidas_rapidas.RECONOCIMIENTO_MEDICO_I.replace("O", "0").astype("float64")
df_historico_comidas_rapidas["TIPO"] = "comidas rapidas"


# %%
import pandas as pd
pd.set_option("max_columns",0)
columns = {
    "MOTIVO":object,
    "NUMERO_ACTA_CONTROL":object,
    "FECHA_VISITA":object,
    "FECHA_INGRESO":object,
    "RAZON_SOCIAL":object,
    "CEDULA_NIT":object,
    "NOMBRE_COMERCIAL":object,
    "MATRICULA_MERCANTIL":object,
    "NUMERO_INSCRIPCION":object,
    "DIRECCION":object,
    "DEPARTAMENTO":object,
    "MUNICIPIO":object,
    "ZONA":object,
    "BARRIO":object,
    "TELEFONO":object,
    "NOMBRE_PROPIETARIO":object,
    "DOCUMENTO_IDENTIFICACION":object,
    "NOMBRE_REPRESENTANTE_LEGAL":object,
    "DOCUMENTO_IDENTIFICACION2":object,
    "DIRECCION_NOTIFICACION":object,

    "LOCALIZACION_Y_CONSTRUCCION_A":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_AR":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_I":"float64",

    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A":object,
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_AR":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_I":"float64",

    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_A":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_AR":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_I":"float64",

    "INSTALACIONES_SANITARIAS_1_A":"float64",
    "INSTALACIONES_SANITARIAS_1_AR":"float64",
    "INSTALACIONES_SANITARIAS_1_I":"float64",

    "EDIFICACION_E_INSTALACIONES":"float64",

    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_A":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_AR":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_I":"float64",

    "SUPERFICIE_CONCATO_ALIMENTO_A":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_AR":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_I":"float64",

    "EQUIPOS_Y_UTENSILIOS":"float64",

    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_A":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_AR":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_I":"float64",

    "RECONOCIMIENTO_MEDICO_A":"float64",
    "RECONOCIMIENTO_MEDICO_AR":"float64",
    "RECONOCIMIENTO_MEDICO_I":"float64",

    "PRACTICAS_HIGIENICAS_Y_DOTACION_A":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_AR":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_I":"float64",

    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_A":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_AR":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_I":"float64",

    "PERSONAL_MANIPULADOR_DE_ALIMENTOS":"float64",

    "CONTROL_MATERIAS_PRIMAS_INSUMOS_A":"float64",
    "CONTROL_MATERIAS_PRIMAS_INSUMOS_AR":"float64",
    "CONTROL_MATERIAS_PRIMAS_INSUMOS_I":"float64",

    "PREVENCION_CONTAMINACION_A":"float64",
    "PREVENCION_CONTAMINACION_I":"float64",

    "MANEJO_TEMPERATURAS_A":"float64",
    "MANEJO_TEMPERATURAS_AR":"float64",
    "MANEJO_TEMPERATURAS_I":"float64",

    "CONDICIONES_ALMACENAMIENTO_A":"float64",
    "CONDICIONES_ALMACENAMIENTO_AR":"float64",
    "CONDICIONES_ALMACENAMIENTO_I":"float64",

    "REQUISITOS_HIGIENICOS": "float64",

    "SUMINISTRO_CALIDAD_AGUA_POTABLE_A":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_AR":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_I":"float64",

    "RESIDUOS_LIQUIDOS_A":"float64",
    "RESIDUOS_LIQUIDOS_AR":"float64",
    "RESIDUOS_LIQUIDOS_I":"float64",

    "RESIDUOS_SOLIDOS_A":"float64",
    "RESIDUOS_SOLIDOS_AR":"float64",
    "RESIDUOS_SOLIDOS_I":"float64",

    "CONTROL_INTEGRAL_PLAGAS_A":"float64",
    "CONTROL_INTEGRAL_PLAGAS_I":"float64",

    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_A":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_AR":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_I":"float64",

    "SOPORTE_DOCUMENTALES_SANEAMIENTO_A":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_AR":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_I":"float64",

    "SANEAMIENTO":"float64",

    "PORCENTAJE_CUMPLIMIENTO":"float64",
    "CUMPLIMIENTO_FAVORABLE_90_100":object,
    "CUMPLIMIENTO_FAVORABLE_80_90":object,
    "CUMPLIMIENTO_FAVORABLE_70_80":object,
    "CUMPLIMIENTO_FAVORABLE_60_70":object,
    "CUMPLIMIENTO_FAVORABLE_0_60":object,

    "REPONSABLE":object,
    "MEDIDA_SANITARIA":object,
    "EMPTY1":object,
    "EMPTY2":object,
}
df_historico_comidas_cafeterias = pd.read_excel("../data/BASE DE DATOS IVC(INSPECCION VIGILANCIA Y CONTROL) 2020.xlsx","CAFETERIAS",skiprows=3,engine='openpyxl', header=None, names=list(columns.keys()), index_col=None, dtype=columns)
df_historico_comidas_cafeterias["CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A"] =  df_historico_comidas_cafeterias.CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A.replace("O", "0").astype("float64")
df_historico_comidas_cafeterias["TIPO"] = "cafeterias"

# %%
import pandas as pd
pd.set_option("max_columns",0)
columns = {
    "MOTIVO":object,
    "NUMERO_ACTA_CONTROL":object,
    "FECHA_VISITA":object,
    "FECHA_INGRESO":object,
    "RAZON_SOCIAL":object,
    "CEDULA_NIT":object,
    "NOMBRE_COMERCIAL":object,
    "MATRICULA_MERCANTIL":object,
    "NUMERO_INSCRIPCION":object,
    "DIRECCION":object,
    "DEPARTAMENTO":object,
    "MUNICIPIO":object,
    "ZONA":object,
    "BARRIO":object,
    "TELEFONO":object,
    "NOMBRE_PROPIETARIO":object,
    "DOCUMENTO_IDENTIFICACION":object,
    "NOMBRE_REPRESENTANTE_LEGAL":object,
    "DOCUMENTO_IDENTIFICACION2":object,
    "DIRECCION_NOTIFICACION":object,

    "LOCALIZACION_Y_CONSTRUCCION_A":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_AR":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_I":"float64",

    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_AR":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_I":"float64",

    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_A":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_AR":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_I":"float64",

    "INSTALACIONES_SANITARIAS_1_A":"float64",
    "INSTALACIONES_SANITARIAS_1_AR":"float64",
    "INSTALACIONES_SANITARIAS_1_I":"float64",

    "EDIFICACION_E_INSTALACIONES":"float64",

    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_A":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_AR":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_I":"float64",

    "SUPERFICIE_CONCATO_ALIMENTO_A":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_AR":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_I":"float64",

    "EQUIPOS_Y_UTENSILIOS":"float64",

    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_A":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_AR":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_I":"float64",

    "RECONOCIMIENTO_MEDICO_A":"float64",
    "RECONOCIMIENTO_MEDICO_AR":"float64",
    "RECONOCIMIENTO_MEDICO_I":"float64",

    "PRACTICAS_HIGIENICAS_Y_DOTACION_A":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_AR":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_I":"float64",

    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_A":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_AR":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_I":"float64",

    "PERSONAL_MANIPULADOR_DE_ALIMENTOS":"float64",

    "CONTROL_MATERIAS_PRIMAS_INSUMOS_A":"float64",
    "CONTROL_MATERIAS_PRIMAS_INSUMOS_AR":"float64",
    "CONTROL_MATERIAS_PRIMAS_INSUMOS_I":"float64",

    "PREVENCION_CONTAMINACION_A":"float64",
    "PREVENCION_CONTAMINACION_I":"float64",

    "MANEJO_TEMPERATURAS_A":"float64",
    "MANEJO_TEMPERATURAS_AR":"float64",
    "MANEJO_TEMPERATURAS_I":"float64",

    "CONDICIONES_ALMACENAMIENTO_A":"float64",
    "CONDICIONES_ALMACENAMIENTO_AR":"float64",
    "CONDICIONES_ALMACENAMIENTO_I":"float64",

    "REQUISITOS_HIGIENICOS": "float64",

    "SUMINISTRO_CALIDAD_AGUA_POTABLE_A":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_AR":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_I":"float64",

    "RESIDUOS_LIQUIDOS_A":"float64",
    "RESIDUOS_LIQUIDOS_AR":"float64",
    "RESIDUOS_LIQUIDOS_I":"float64",

    "RESIDUOS_SOLIDOS_A":"float64",
    "RESIDUOS_SOLIDOS_AR":"float64",
    "RESIDUOS_SOLIDOS_I":"float64",

    "CONTROL_INTEGRAL_PLAGAS_A":"float64",
    "CONTROL_INTEGRAL_PLAGAS_I":"float64",

    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_A":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_AR":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_I":"float64",

    "SOPORTE_DOCUMENTALES_SANEAMIENTO_A":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_AR":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_I":"float64",

    "SANEAMIENTO":"float64",

    "PORCENTAJE_CUMPLIMIENTO":"float64",
    "CUMPLIMIENTO_FAVORABLE_90_100":object,
    "CUMPLIMIENTO_FAVORABLE_80_90":object,
    "CUMPLIMIENTO_FAVORABLE_70_80":object,
    "CUMPLIMIENTO_FAVORABLE_60_70":object,
    "CUMPLIMIENTO_FAVORABLE_0_60":object,

    "REPONSABLE":object,
    "MEDIDA_SANITARIA":object,
    "EMPTY1":object,
    "EMPTY2":object,
    "EMPTY3":object,
    "EMPTY4":object,
    "EMPTY5":object,
    "EMPTY6":object,
}
df_historico_comidas_heladerias_fruterias_postrerias = pd.read_excel("../data/BASE DE DATOS IVC(INSPECCION VIGILANCIA Y CONTROL) 2020.xlsx","HELADERIAS-FRUTERIAS-POSTRERIAS",skiprows=3,engine='openpyxl', header=None, names=list(columns.keys()), index_col=None, dtype=columns)
df_historico_comidas_heladerias_fruterias_postrerias["TIPO"] = "heladerias fruterias postrerias"

# %%


# %%
import pandas as pd
pd.set_option("max_columns",0)
columns = {
    "MOTIVO":object,
    "NUMERO_ACTA_VISITA":object,
    "NUMERO_ACTA_CONTROL":object,
    "FECHA_VISITA":object,
    "FECHA_INGRESO":object,
    "RAZON_SOCIAL":object,
    "CEDULA_NIT":object,
    "NOMBRE_COMERCIAL":object,
    "MATRICULA_MERCANTIL":object,
    "NUMERO_INSCRIPCION":object,
    "DIRECCION":object,
    "DEPARTAMENTO":object,
    "MUNICIPIO":object,
    "ZONA":object,
    "BARRIO":object,
    "TELEFONO":object,
    "NOMBRE_PROPIETARIO":object,
    "DOCUMENTO_IDENTIFICACION":object,
    "NOMBRE_REPRESENTANTE_LEGAL":object,
    "EMPTY":object,
    "DOCUMENTO_IDENTIFICACION2":object,
    "DIRECCION_NOTIFICACION":object,

    "LOCALIZACION_Y_CONSTRUCCION_A":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_AR":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_I":"float64",

    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_AR":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_I":"float64",

    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_A":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_AR":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_I":"float64",

    "INSTALACIONES_SANITARIAS_1_A":"float64",
    "INSTALACIONES_SANITARIAS_1_AR":"float64",
    "INSTALACIONES_SANITARIAS_1_I":"float64",

    "INSTALACIONES_SANITARIAS_2_A":"float64",
    "INSTALACIONES_SANITARIAS_2_AR":"float64",
    "INSTALACIONES_SANITARIAS_2_I":"float64",

    "EDIFICACION_E_INSTALACIONES":"float64",

    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_A":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_AR":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_I":"float64",

    "SUPERFICIE_CONCATO_ALIMENTO_A":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_AR":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_I":"float64",

    "EQUIPOS_Y_UTENSILIOS":"float64",

    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_A":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_AR":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_I":"float64",

    "RECONOCIMIENTO_MEDICO_A":"float64",
    "RECONOCIMIENTO_MEDICO_AR":"float64",
    "RECONOCIMIENTO_MEDICO_I":"float64",

    "PRACTICAS_HIGIENICAS_Y_DOTACION_A":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_AR":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_I":"float64",

    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_A":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_AR":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_I":"float64",

    "PERSONAL_MANIPULADOR_DE_ALIMENTOS":"float64",

    "SUMINISTRO_CALIDAD_AGUA_POTABLE_A":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_AR":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_I":"float64",

    "RESIDUOS_LIQUIDOS_A":"float64",
    "RESIDUOS_LIQUIDOS_AR":"float64",
    "RESIDUOS_LIQUIDOS_I":"float64",

    "RESIDUOS_SOLIDOS_A":"float64",
    "RESIDUOS_SOLIDOS_AR":"float64",
    "RESIDUOS_SOLIDOS_I":"float64",

    "CONTROL_INTEGRAL_PLAGAS_A":"float64",
    "CONTROL_INTEGRAL_PLAGAS_I":"float64",

    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_A":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_AR":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_I":"float64",

    "SOPORTE_DOCUMENTALES_SANEAMIENTO_A":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_AR":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_I":"float64",

    "SANEAMIENTO":"float64",

    "CONDICIONES_ALMACENAMIENTO_A":"float64",
    "CONDICIONES_ALMACENAMIENTO_AR":"float64",
    "CONDICIONES_ALMACENAMIENTO_I":"float64",

    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_A": "float64",
    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_AR": "float64",
    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_I": "float64",

    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_A": "float64",
    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_AR": "float64",
    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_I": "float64",

    "ALMACENAMIENTO_Y_COMERCIALIZACION": "float64",

    "PROCEDENCIA_REQUISITOS_LEGALES_A": "float64",
    "PROCEDENCIA_REQUISITOS_LEGALES_AR": "float64",
    "PROCEDENCIA_REQUISITOS_LEGALES_I": "float64",

    "REQUISITOS_LEGALES":"float64",

    "PORCENTAJE_CUMPLIMIENTO":"float64",
    "CUMPLIMIENTO_FAVORABLE_90_100":object,
    "CUMPLIMIENTO_FAVORABLE_80_90":object,
    "CUMPLIMIENTO_FAVORABLE_70_80":object,
    "CUMPLIMIENTO_FAVORABLE_60_70":object,
    "CUMPLIMIENTO_FAVORABLE_0_60":object,

    "REPONSABLE":object,
    "MEDIDA_SANITARIA":object,
    "EMPTY1":object,
    "EMPTY2":object,
    "EMPTY3":object,
    "EMPTY4":object,
    "EMPTY5":object,
    "EMPTY6":object,
}
df_historico_autoservicios = pd.read_excel("../data/BASE DE DATOS IVC(INSPECCION VIGILANCIA Y CONTROL) 2020.xlsx","AUTOSERVICIOS",skiprows=3,engine='openpyxl', header=None, names=list(columns.keys()), index_col=None, dtype=columns)
df_historico_autoservicios["TIPO"] = "autoservicios"

# %%
import pandas as pd
pd.set_option("max_columns",0)
columns = {
    "MOTIVO":object,
    "NUMERO_ACTA_VISITA":object,
    "NUMERO_ACTA_CONTROL":object,
    "FECHA_VISITA":object,
    "FECHA_INGRESO":object,
    "RAZON_SOCIAL":object,
    "CEDULA_NIT":object,
    "NOMBRE_COMERCIAL":object,
    "MATRICULA_MERCANTIL":object,
    "NUMERO_INSCRIPCION":object,
    "DIRECCION":object,
    "DEPARTAMENTO":object,
    "MUNICIPIO":object,
    "ZONA":object,
    "BARRIO":object,
    "TELEFONO":object,
    "NOMBRE_PROPIETARIO":object,
    "DOCUMENTO_IDENTIFICACION":object,
    "NOMBRE_REPRESENTANTE_LEGAL":object,
    "EMPTY":object,
    "DOCUMENTO_IDENTIFICACION2":object,
    "DIRECCION_NOTIFICACION":object,

    "LOCALIZACION_Y_CONSTRUCCION_A":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_AR":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_I":"float64",

    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_AR":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_I":"float64",

    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_A":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_AR":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_I":"float64",

    "INSTALACIONES_SANITARIAS_1_A":"float64",
    "INSTALACIONES_SANITARIAS_1_AR":"float64",
    "INSTALACIONES_SANITARIAS_1_I":"float64",

    "INSTALACIONES_SANITARIAS_2_A":"float64",
    "INSTALACIONES_SANITARIAS_2_AR":"float64",
    "INSTALACIONES_SANITARIAS_2_I":"float64",

    "EDIFICACION_E_INSTALACIONES":"float64",

    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_A":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_AR":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_I":"float64",

    "SUPERFICIE_CONCATO_ALIMENTO_A":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_AR":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_I":"float64",

    "EQUIPOS_Y_UTENSILIOS":"float64",

    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_A":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_AR":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_I":"float64",

    "RECONOCIMIENTO_MEDICO_A":"float64",
    "RECONOCIMIENTO_MEDICO_AR":"float64",
    "RECONOCIMIENTO_MEDICO_I":"float64",

    "PRACTICAS_HIGIENICAS_Y_DOTACION_A":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_AR":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_I":"float64",

    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_A":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_AR":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_I":"float64",

    "PERSONAL_MANIPULADOR_DE_ALIMENTOS":"float64",

    "SUMINISTRO_CALIDAD_AGUA_POTABLE_A":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_AR":object,
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_I":"float64",

    "RESIDUOS_LIQUIDOS_A":"float64",
    "RESIDUOS_LIQUIDOS_AR":"float64",
    "RESIDUOS_LIQUIDOS_I":"float64",

    "RESIDUOS_SOLIDOS_A":"float64",
    "RESIDUOS_SOLIDOS_AR":"float64",
    "RESIDUOS_SOLIDOS_I":"float64",

    "CONTROL_INTEGRAL_PLAGAS_A":"float64",
    "CONTROL_INTEGRAL_PLAGAS_I":"float64",

    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_A":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_AR":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_I":"float64",

    "SOPORTE_DOCUMENTALES_SANEAMIENTO_A":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_AR":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_I":"float64",

    "SANEAMIENTO":"float64",

    "CONDICIONES_ALMACENAMIENTO_A":"float64",
    "CONDICIONES_ALMACENAMIENTO_AR":"float64",
    "CONDICIONES_ALMACENAMIENTO_I":"float64",

    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_A": "float64",
    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_AR": "float64",
    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_I": "float64",

    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_A": "float64",
    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_AR": "float64",
    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_I": "float64",

    "ALMACENAMIENTO_Y_COMERCIALIZACION": "float64",

    "PROCEDENCIA_REQUISITOS_LEGALES_A": "float64",
    "PROCEDENCIA_REQUISITOS_LEGALES_AR": "float64",
    "PROCEDENCIA_REQUISITOS_LEGALES_I": "float64",

    "REQUISITOS_LEGALES":"float64",

    "PORCENTAJE_CUMPLIMIENTO":"float64",
    "CUMPLIMIENTO_FAVORABLE_90_100":object,
    "CUMPLIMIENTO_FAVORABLE_80_90":object,
    "CUMPLIMIENTO_FAVORABLE_70_80":object,
    "CUMPLIMIENTO_FAVORABLE_60_70":object,
    "CUMPLIMIENTO_FAVORABLE_0_60":object,

    "REPONSABLE":object,
    "MEDIDA_SANITARIA":object,
    "EMPTY1":object,
    "EMPTY2":object,
    "EMPTY3":object,
    "EMPTY4":object,
    "EMPTY5":object,
    "EMPTY6":object,
}
df_historico_supermercados = pd.read_excel("../data/BASE DE DATOS IVC(INSPECCION VIGILANCIA Y CONTROL) 2020.xlsx","SUPERMERCADOS",skiprows=3,engine='openpyxl', header=None, names=list(columns.keys()), index_col=None, dtype=columns)
df_historico_supermercados["SUMINISTRO_CALIDAD_AGUA_POTABLE_AR"] = df_historico_supermercados.SUMINISTRO_CALIDAD_AGUA_POTABLE_AR.apply(lambda x: str(x).replace("..", ".")).astype("float64")
df_historico_supermercados["TIPO"] = "supermercados"

# %%
import pandas as pd
pd.set_option("max_columns",0)
columns = {
    "EMPTY":object,
    "MOTIVO":object,
    "NUMERO_ACTA_VISITA":object,
    "NUMERO_ACTA_CONTROL":object,
    "FECHA_VISITA":object,
    "FECHA_INGRESO":object,
    "RAZON_SOCIAL":object,
    "CEDULA_NIT":object,
    "NOMBRE_COMERCIAL":object,
    "NUMERO_INSCRIPCION":object,
    "MATRICULA_MERCANTIL":object,
    "DIRECCION":object,
    "DEPARTAMENTO":object,
    "MUNICIPIO":object,
    "ZONA":object,
    "BARRIO":object,
    "TELEFONO":object,
    "NOMBRE_PROPIETARIO":object,
    "DOCUMENTO_IDENTIFICACION":object,
    "NOMBRE_REPRESENTANTE_LEGAL":object,
    "EMPTY0":object,
    "DOCUMENTO_IDENTIFICACION2":object,
    "DIRECCION_NOTIFICACION":object,

    "LOCALIZACION_Y_CONSTRUCCION_A":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_AR":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_I":"float64",

    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_AR":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_I":"float64",

    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_A":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_AR":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_I":"float64",

    "INSTALACIONES_SANITARIAS_1_A":"float64",
    "INSTALACIONES_SANITARIAS_1_AR":"float64",
    "INSTALACIONES_SANITARIAS_1_I":"float64",

    "INSTALACIONES_SANITARIAS_2_A":"float64",
    "INSTALACIONES_SANITARIAS_2_AR":"float64",
    "INSTALACIONES_SANITARIAS_2_I":"float64",

    "EDIFICACION_E_INSTALACIONES":"float64",

    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_A":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_AR":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_I":"float64",

    "SUPERFICIE_CONCATO_ALIMENTO_A":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_AR":"float64",
    "SUPERFICIE_CONCATO_ALIMENTO_I":"float64",

    "EQUIPOS_Y_UTENSILIOS":"float64",

    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_A":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_AR":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_I":"float64",

    "RECONOCIMIENTO_MEDICO_A":"float64",
    "RECONOCIMIENTO_MEDICO_AR":"float64",
    "RECONOCIMIENTO_MEDICO_I":"float64",

    "PRACTICAS_HIGIENICAS_Y_DOTACION_A":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_AR":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_I":"float64",

    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_A":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_AR":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_I":"float64",

    "PERSONAL_MANIPULADOR_DE_ALIMENTOS":"float64",

    "SUMINISTRO_CALIDAD_AGUA_POTABLE_A":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_AR":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_I":"float64",

    "RESIDUOS_LIQUIDOS_A":"float64",
    "RESIDUOS_LIQUIDOS_AR":"float64",
    "RESIDUOS_LIQUIDOS_I":"float64",

    "RESIDUOS_SOLIDOS_A":"float64",
    "RESIDUOS_SOLIDOS_AR":"float64",
    "RESIDUOS_SOLIDOS_I":"float64",

    "CONTROL_INTEGRAL_PLAGAS_A":"float64",
    "CONTROL_INTEGRAL_PLAGAS_I":"float64",

    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_A":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_AR":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_I":"float64",

    "SOPORTE_DOCUMENTALES_SANEAMIENTO_A":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_AR":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_I":"float64",

    "SANEAMIENTO":"float64",

    "CONDICIONES_ALMACENAMIENTO_A":"float64",
    "CONDICIONES_ALMACENAMIENTO_AR":"float64",
    "CONDICIONES_ALMACENAMIENTO_I":"float64",

    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_A": "float64",
    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_AR": "float64",
    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_I": "float64",

    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_A": "float64",
    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_AR": "float64",
    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_I": "float64",

    "ALMACENAMIENTO_Y_COMERCIALIZACION": "float64",

    "PROCEDENCIA_REQUISITOS_LEGALES_A": "float64",
    "PROCEDENCIA_REQUISITOS_LEGALES_AR": "float64",
    "PROCEDENCIA_REQUISITOS_LEGALES_I": "float64",

    "REQUISITOS_LEGALES":"float64",

    "PORCENTAJE_CUMPLIMIENTO":"float64",
    "CUMPLIMIENTO_FAVORABLE_90_100":object,
    "CUMPLIMIENTO_FAVORABLE_80_90":object,
    "CUMPLIMIENTO_FAVORABLE_70_80":object,
    "CUMPLIMIENTO_FAVORABLE_60_70":object,
    "CUMPLIMIENTO_FAVORABLE_0_60":object,

    "REPONSABLE":object,
    "MEDIDA_SANITARIA":object,
    "EMPTY1":object,
    "EMPTY2":object,
    "EMPTY3":object,
}
df_historico_distribuidoras = pd.read_excel("../data/BASE DE DATOS IVC(INSPECCION VIGILANCIA Y CONTROL) 2020.xlsx","DISTRIBUIDORAS",skiprows=3,engine='openpyxl', header=None, names=list(columns.keys()), index_col=None, dtype=columns)
df_historico_distribuidoras["TIPO"] = "distribuidores"

# %%
import pandas as pd
pd.set_option("max_columns",0)
columns = {
    "MOTIVO":object,
    "NUMERO_ACTA_CONTROL":object,
    "FECHA_VISITA":object,
    "FECHA_INGRESO":object,
    "RAZON_SOCIAL":object,
    "CEDULA_NIT":object,
    "NOMBRE_COMERCIAL":object,
    "NUMERO_INSCRIPCION":object,
    "DIRECCION":object,
    "DEPARTAMENTO":object,
    "MUNICIPIO":object,
    "ZONA":object,
    "BARRIO":object,
    "TELEFONO":object,
    "NOMBRE_PROPIETARIO":object,
    "DOCUMENTO_IDENTIFICACION":object,
    "NOMBRE_REPRESENTANTE_LEGAL":object,
    "DOCUMENTO_IDENTIFICACION2":object,
    "DIRECCION_NOTIFICACION":object,

    "LOCALIZACION_Y_CONSTRUCCION_A":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_AR":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_I":"float64",

    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_AR":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_I":"float64",

    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_A":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_AR":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_I":"float64",

    "INSTALACIONES_SANITARIAS_1_A":"float64",
    "INSTALACIONES_SANITARIAS_1_AR":"float64",
    "INSTALACIONES_SANITARIAS_1_I":"float64",

    "EDIFICACION_E_INSTALACIONES":"float64",

    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_A":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_AR":"float64",
    "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_I":"float64",

    "EQUIPOS_Y_UTENSILIOS":"float64",

    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_A":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_AR":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_I":"float64",

    "RECONOCIMIENTO_MEDICO_A":"float64",
    "RECONOCIMIENTO_MEDICO_AR":"float64",
    "RECONOCIMIENTO_MEDICO_I":"float64",

    "PRACTICAS_HIGIENICAS_Y_DOTACION_A":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_AR":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_I":"float64",

    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_A":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_AR":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_I":"float64",

    "PERSONAL_MANIPULADOR_DE_ALIMENTOS":"float64",

    "RECEPCION_REQUISITOS_LEGALES_A":"float64",
    "RECEPCION_REQUISITOS_LEGALES_AR":"float64",
    "RECEPCION_REQUISITOS_LEGALES_I":"float64",

    "CONDICIONES_ALMACENAMIENTO_A":"float64",
    "CONDICIONES_ALMACENAMIENTO_AR":"float64",
    "CONDICIONES_ALMACENAMIENTO_I":"float64",

    "CONSERVACION_PRODUCTOS_A":"float64",
    "CONSERVACION_PRODUCTOS_AR":"float64",
    "CONSERVACION_PRODUCTOS_I":"float64",
    
    "REQUISITOS_HIGIENICOS": "float64",

    "SUMINISTRO_CALIDAD_AGUA_POTABLE_A":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_AR":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_I":"float64",

    "RESIDUOS_LIQUIDOS_A":"float64",
    "RESIDUOS_LIQUIDOS_AR":"float64",
    "RESIDUOS_LIQUIDOS_I":"float64",

    "RESIDUOS_SOLIDOS_A":"float64",
    "RESIDUOS_SOLIDOS_AR":"float64",
    "RESIDUOS_SOLIDOS_I":"float64",

    "CONTROL_INTEGRAL_PLAGAS_A":"float64",
    "CONTROL_INTEGRAL_PLAGAS_I":"float64",

    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_A":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_AR":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_I":"float64",

    "SOPORTE_DOCUMENTALES_SANEAMIENTO_A":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_AR":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_I":"float64",

    "SANEAMIENTO":"float64",

    "PORCENTAJE_CUMPLIMIENTO":"float64",
    "CUMPLIMIENTO_FAVORABLE_90_100":object,
    "CUMPLIMIENTO_FAVORABLE_80_90":object,
    "CUMPLIMIENTO_FAVORABLE_70_80":object,
    "CUMPLIMIENTO_FAVORABLE_60_70":object,
    "CUMPLIMIENTO_FAVORABLE_0_60":object,

    "REPONSABLE":object,
    "MEDIDA_SANITARIA":object,
    "EMPTY1":object,
    "EMPTY2":object,
    "EMPTY3":object,
    "EMPTY4":object,
    "EMPTY5":object,
    "EMPTY6":object,
}
df_historico_hogares_bienestar = pd.read_excel("../data/BASE DE DATOS IVC(INSPECCION VIGILANCIA Y CONTROL) 2020.xlsx","HOGARES DE BIENESTAR",skiprows=3,engine='openpyxl', header=None, names=list(columns.keys()), index_col=None, dtype=columns)
df_historico_hogares_bienestar["TIPO"] = "hogares de bienestar"

# %%
import pandas as pd
pd.set_option("max_columns",0)
columns = {
    "MOTIVO":object,
    "NUMERO_ACTA_CONTROL":object,
    "FECHA_VISITA":object,
    "FECHA_INGRESO":object,
    "RAZON_SOCIAL":object,
    "CEDULA_NIT":object,
    "NOMBRE_COMERCIAL":object,
    "NUMERO_INSCRIPCION":object,
    "DIRECCION":object,
    "DEPARTAMENTO":object,
    "MUNICIPIO":object,
    "BARRIO":object,
    "NOMBRE_PROPIETARIO":object,
    "TELEFONO":object,
    "DOCUMENTO_IDENTIFICACION":object,
    "NOMBRE_REPRESENTANTE_LEGAL":object,
    "DOCUMENTO_IDENTIFICACION2":object,
    "DIRECCION_NOTIFICACION":object,

    "LOCALIZACION_Y_CONSTRUCCION_A":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_AR":"float64",
    "LOCALIZACION_Y_CONSTRUCCION_I":"float64",

    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_AR":"float64",
    "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_I":"float64",

    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_A":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_AR":"float64",
    "TECHOS_PUERTAS_ILUMINACION_VENTILACION_I":"float64",

    "INSTALACIONES_SANITARIAS_1_A":"float64",
    "INSTALACIONES_SANITARIAS_1_AR":"float64",
    "INSTALACIONES_SANITARIAS_1_I":"float64",

    "EDIFICACION_E_INSTALACIONES":"float64",

    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_A":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_AR":"float64",
    "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_I":"float64",

    "PRACTICAS_HIGIENICAS_Y_DOTACION_A":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_AR":"float64",
    "PRACTICAS_HIGIENICAS_Y_DOTACION_I":"float64",

    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_A":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_AR":"float64",
    "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_I":"float64",

    "PERSONAL_MANIPULADOR_DE_ALIMENTOS":"float64",

    "CONDICIONES_EQUIPOS_UTENSILIOS_SUPERFICIES_CONTACTO_A":"float64",
    "CONDICIONES_EQUIPOS_UTENSILIOS_SUPERFICIES_CONTACTO_AR":"float64",
    "CONDICIONES_EQUIPOS_UTENSILIOS_SUPERFICIES_CONTACTO_I":"float64",

    "PREVENCION_CONTAMINACION_CRUZADA_A":"float64",
    "PREVENCION_CONTAMINACION_CRUZADA_AR":"float64",
    "PREVENCION_CONTAMINACION_CRUZADA_I":"float64",

    "CONDICIONES_ALMACENAMIENTO_A":"float64",
    "CONDICIONES_ALMACENAMIENTO_AR":"float64",
    "CONDICIONES_ALMACENAMIENTO_I":"float64",

    "CONDICIONES_ALMACENAMIENTO": "float64",

    "SUMINISTRO_CALIDAD_AGUA_POTABLE_A":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_AR":"float64",
    "SUMINISTRO_CALIDAD_AGUA_POTABLE_I":"float64",

    "RESIDUOS_LIQUIDOS_A":"float64",
    "RESIDUOS_LIQUIDOS_AR":"float64",
    "RESIDUOS_LIQUIDOS_I":"float64",

    "RESIDUOS_SOLIDOS_A":"float64",
    "RESIDUOS_SOLIDOS_AR":"float64",
    "RESIDUOS_SOLIDOS_I":"float64",

    "CONTROL_INTEGRAL_PLAGAS_A":"float64",
    "EMPTY9":object,
    "CONTROL_INTEGRAL_PLAGAS_I":"float64",

    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_A":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_AR":"float64",
    "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_I":"float64",

    "SOPORTE_DOCUMENTALES_SANEAMIENTO_A":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_AR":"float64",
    "SOPORTE_DOCUMENTALES_SANEAMIENTO_I":"float64",

    "SANEAMIENTO":"float64",

    "PROCEDENCIA_BEBIDAS_ALCOHOLICAS_A":"float64",
    "PROCEDENCIA_BEBIDAS_ALCOHOLICAS_AR":"float64",
    "PROCEDENCIA_BEBIDAS_ALCOHOLICAS_I":"float64",

    "LEYENDAS_OBLIGATORIAS_A":"float64",
    "LEYENDAS_OBLIGATORIAS_AR":"float64",
    "LEYENDAS_OBLIGATORIAS_I":"float64",

    "VERIFICACION_SOBRE_PRODUCTO":"float64",

    "PORCENTAJE_CUMPLIMIENTO":"float64",
    "CUMPLIMIENTO_FAVORABLE_90_100":object,
    "CUMPLIMIENTO_FAVORABLE_80_90":object,
    "CUMPLIMIENTO_FAVORABLE_70_80":object,
    "CUMPLIMIENTO_FAVORABLE_60_70":object,
    "CUMPLIMIENTO_FAVORABLE_0_60":object,

    "REPONSABLE":object,
    "MEDIDA_SANITARIA":object,
    "EMPTY1":object,
    "EMPTY2":object,
    "EMPTY3":object,
    "EMPTY4":object,
    "EMPTY5":object,
    "EMPTY6":object,
}
df_historico_bebidas_alcoholicas = pd.read_excel("../data/BASE DE DATOS IVC(INSPECCION VIGILANCIA Y CONTROL) 2020.xlsx","BEBIDAS ALCOHÓLICAS",skiprows=4,engine='openpyxl', header=None, names=list(columns.keys()), index_col=None, dtype=columns)
df_historico_bebidas_alcoholicas["TIPO"] = "bebidas alcoholicas"

# In[ ]:
df_all  = pd.concat([
    df_historico_tiendas, 
    df_historico_panaderias,
    df_historico_restaurantes,
    df_historico_comidas_rapidas,
    df_historico_comidas_cafeterias,
    df_historico_comidas_heladerias_fruterias_postrerias,
    df_historico_autoservicios,
    df_historico_supermercados,
    df_historico_distribuidoras,
    df_historico_hogares_bienestar,
    df_historico_bebidas_alcoholicas
], axis=0)

df_all.shape

# In[ ]:

df_all.head()
df_all.dtypes

# In[ ]:
df_floats = df_all.select_dtypes(include=["float64"])
df_floats.TECHOS_PUERTAS_ILUMINACION_VENTILACION_A.describe()

# In[ ]:
df_all.select_dtypes(include=["object"]).columns.values
df_all.shape
# In[ ]:
import json
from sqlalchemy.orm import sessionmaker
from sqlalchemy import create_engine

def get_engine():
    engine = create_engine(f'mssql+pyodbc://sa:Ds4all43@192.168.1.14/sogamoso?driver=ODBC+Driver+18+for+SQL+Server;Encrypt=No', echo=False)
    return engine

def get_value(value):
    if value is None:
        return ""
    return str(value).replace("'", "''")
    

def save_to_db(df, connection, columns, Session):
    with Session(bind=connection) as session:
        records = json.loads(df.to_json(orient='records'))
        for record in records:
            table_columns = []
            table_values  = []
            for columnName, columnType in columns.items():
                table_columns.append(columnName)
                if columnType == "object":
                    value = "'"+get_value(record.get(columnName))+"'"
                    table_values.append(value)

                elif columnType == "float64":
                    value = record.get(columnName)
                    if not value:
                        table_values.append("0")
                    else:
                        table_values.append(str(value))
            strColumns = ",".join(table_columns)
            strValues = ",".join(table_values)
            connection.execute(f"INSERT INTO VISITA_SANITARIA ({strColumns}) VALUES ({strValues})")
            print(".", end="")
        session.commit()            
engine = get_engine()
Session = sessionmaker(engine)
connection = engine.connect()

with Session(bind=connection) as session:
    connection.execute("DELETE FROM VISITA_SANITARIA")
    session.commit()

columns = {
    "TIPO":"object",
    "MOTIVO":"object",
    "NUMERO_ACTA_CONTROL":"object",
    "NUMERO_ACTA_VISITA":"object",
    "NUMERO_INSCRIPCION":"object",
    "RAZON_SOCIAL":"object",
    "CEDULA_NIT":"object",
    "NOMBRE_COMERCIAL":"object",
    "MATRICULA_MERCANTIL":"object",
    "DIRECCION":"object",
    "DIRECCION_NOTIFICACION":"object",
    "DEPARTAMENTO":"object",
    "MUNICIPIO":"object",
    "ZONA":"object",
    "BARRIO":"object",
    "NOMBRE_REPRESENTANTE_LEGAL":"object",
    "TELEFONO":"object",
    "REPONSABLE":"object",
    "NOMBRE_PROPIETARIO":"object",
    "DOCUMENTO_IDENTIFICACION":"object",
    "MEDIDA_SANITARIA":"object",

    "EDIFICACION_E_INSTALACIONES":"float64",
        "LOCALIZACION_Y_CONSTRUCCION_A":"float64",
        "LOCALIZACION_Y_CONSTRUCCION_AR":"float64",
        "LOCALIZACION_Y_CONSTRUCCION_I":"float64",

        "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_A":"float64",
        "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_AR":"float64",
        "CONDICIONES_PISOS_PAREDES_Y_DRENAJES_I":"float64",

        "TECHOS_PUERTAS_ILUMINACION_VENTILACION_A":"float64",
        "TECHOS_PUERTAS_ILUMINACION_VENTILACION_AR":"float64",
        "TECHOS_PUERTAS_ILUMINACION_VENTILACION_I":"float64",

        "INSTALACIONES_SANITARIAS_1_A":"float64",
        "INSTALACIONES_SANITARIAS_1_AR":"float64",
        "INSTALACIONES_SANITARIAS_1_I":"float64",

        "INSTALACIONES_SANITARIAS_2_A":"float64",
        "INSTALACIONES_SANITARIAS_2_AR":"float64",
        "INSTALACIONES_SANITARIAS_2_I":"float64",
    
    "EQUIPOS_Y_UTENSILIOS":"float64",
        "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_A":"float64",
        "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_AR":"float64",
        "CAPACIDAD_DISENO_FUNCIONAMIENTO_EQUIPOS_UTENSILIOS_I":"float64",

        "SUPERFICIE_CONCATO_ALIMENTO_A":"float64",
        "SUPERFICIE_CONCATO_ALIMENTO_AR":"float64",
        "SUPERFICIE_CONCATO_ALIMENTO_I":"float64",

    "PERSONAL_MANIPULADOR_DE_ALIMENTOS":"float64",    
        "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_A":"float64",
        "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_AR":"float64",
        "ESTADO_SALUD_APARENTE_SIGNOS_LESIONES_I":"float64",

        "RECONOCIMIENTO_MEDICO_A":"float64",
        "RECONOCIMIENTO_MEDICO_AR":"float64",
        "RECONOCIMIENTO_MEDICO_I":"float64",

        "PRACTICAS_HIGIENICAS_Y_DOTACION_A":"float64",
        "PRACTICAS_HIGIENICAS_Y_DOTACION_AR":"float64",
        "PRACTICAS_HIGIENICAS_Y_DOTACION_I":"float64",

        "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_A":"float64",
        "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_AR":"float64",
        "CAPACITACION_MANIPULACION_HIGIENICA_ALIMENTOS_I":"float64",

    "SANEAMIENTO":"float64",

        "SUMINISTRO_CALIDAD_AGUA_POTABLE_A":"float64",
        "SUMINISTRO_CALIDAD_AGUA_POTABLE_AR":"float64",
        "SUMINISTRO_CALIDAD_AGUA_POTABLE_I":"float64",

        "RESIDUOS_LIQUIDOS_A":"float64",
        "RESIDUOS_LIQUIDOS_AR":"float64",
        "RESIDUOS_LIQUIDOS_I":"float64",

        "RESIDUOS_SOLIDOS_A":"float64",
        "RESIDUOS_SOLIDOS_AR":"float64",
        "RESIDUOS_SOLIDOS_I":"float64",

        "CONTROL_INTEGRAL_PLAGAS_A":"float64",
        "CONTROL_INTEGRAL_PLAGAS_I":"float64",

        "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_A":"float64",
        "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_AR":"float64",
        "LIMPIEZA_DESINFECCION_AREAS_EQUIPOS_UTENSILIOS_I":"float64",

        "SOPORTE_DOCUMENTALES_SANEAMIENTO_A":"float64",
        "SOPORTE_DOCUMENTALES_SANEAMIENTO_AR":"float64",
        "SOPORTE_DOCUMENTALES_SANEAMIENTO_I":"float64",

    
    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_A":"float64",
    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_AR":"float64",
    "MANEJO_CONSERVACION_PRODUCTOS_REFRIGERADOS_CONGELADOS_I":"float64",

    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_A":"float64",
    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_AR":"float64",
    "MANEJO_PRODUCTOS_EXPENDEN_A_TEMPERATURA_AMBIENTE_I":"float64",

    "CONDICIONES_EQUIPOS_UTENSILIOS_SUPERFICIES_CONTACTO_A":"float64",
    "CONDICIONES_EQUIPOS_UTENSILIOS_SUPERFICIES_CONTACTO_AR":"float64",
    "CONDICIONES_EQUIPOS_UTENSILIOS_SUPERFICIES_CONTACTO_I":"float64",

    "PREVENCION_CONTAMINACION_CRUZADA_A":"float64",
    "PREVENCION_CONTAMINACION_CRUZADA_AR":"float64",
    "PREVENCION_CONTAMINACION_CRUZADA_I":"float64",

    "CONDICIONES_ALMACENAMIENTO_A":"float64",
    "CONDICIONES_ALMACENAMIENTO_AR":"float64",
    "CONDICIONES_ALMACENAMIENTO_I":"float64",

    "MANEJO_TEMPERATURAS_A":"float64",
    "MANEJO_TEMPERATURAS_AR":"float64",
    "MANEJO_TEMPERATURAS_I":"float64",

    "CONTROL_MATERIAS_PRIMAS_INSUMOS_A":"float64",
    "CONTROL_MATERIAS_PRIMAS_INSUMOS_AR":"float64",
    "CONTROL_MATERIAS_PRIMAS_INSUMOS_I":"float64",

    "CONSERVACION_PRODUCTOS_A":"float64",
    "CONSERVACION_PRODUCTOS_AR":"float64",
    "CONSERVACION_PRODUCTOS_I":"float64",

    "RECEPCION_REQUISITOS_LEGALES_A":"float64",
    "RECEPCION_REQUISITOS_LEGALES_AR":"float64",
    "RECEPCION_REQUISITOS_LEGALES_I":"float64",

    "PREVENCION_CONTAMINACION_A":"float64",
    "PREVENCION_CONTAMINACION_AR":"float64",
    "PREVENCION_CONTAMINACION_I":"float64",

    "PROCEDENCIA_REQUISITOS_LEGALES_A":"float64",
    "PROCEDENCIA_REQUISITOS_LEGALES_AR":"float64",
    "PROCEDENCIA_REQUISITOS_LEGALES_I":"float64",

    "LEYENDAS_OBLIGATORIAS_A":"float64",
    "LEYENDAS_OBLIGATORIAS_AR":"float64",
    "LEYENDAS_OBLIGATORIAS_I":"float64",

    "PROCEDENCIA_BEBIDAS_ALCOHOLICAS_A":"float64",
    "PROCEDENCIA_BEBIDAS_ALCOHOLICAS_AR":"float64",
    "PROCEDENCIA_BEBIDAS_ALCOHOLICAS_I":"float64",


    "CONDICIONES_ALMACENAMIENTO": "float64",

    "PORCENTAJE_CUMPLIMIENTO":"float64"
}

save_to_db(df_all,connection, columns, Session)

print("saving process finished")